# Generated by Django 5.1.5 on 2025-02-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='group_name2',
        ),
    ]
