# Generated by Django 5.1.5 on 2025-02-04 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0002_remove_chatgroup_group_name2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='users_online',
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='users_online',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='online_in_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
