# Generated by Django 5.1.5 on 2025-02-05 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0004_remove_chatgroup_users_online_chatgroup_users_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='users_online',
        ),
    ]
