# Generated by Django 5.1.5 on 2025-02-06 00:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0006_chatroom_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatRoom_Members',
            new_name='ChatRoom_Member',
        ),
    ]
