# Generated by Django 5.1.5 on 2025-02-06 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0007_rename_chatroom_members_chatroom_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom_member',
            old_name='participants',
            new_name='participant',
        ),
    ]
