# Generated by Django 5.1.5 on 2025-02-06 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0009_alter_chatroom_member_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom_member',
            name='chatroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_members', to='a_rtchat.chatroom'),
        ),
    ]
