# Generated by Django 5.1.5 on 2025-02-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0011_remove_groupmessage_group_remove_groupmessage_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
